services:
  redis:
    image: redis:7-alpine
    container_name: tma-redis
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "127.0.0.1:6379:6379"
    command: >
      redis-server 
      --appendonly yes 
      --replica-read-only no 
      --requirepass "${REDIS_PASSWORD}"
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
      - ./logs:/app/logs
      - ./container-logs:/var/log/app
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - tma-network
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tma-backend
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "6001:6001"
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      FRONTEND_URL: ${FRONTEND_URL}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      ZEPHYR_SECRET_KEY: ${ZEPHYR_SECRET_KEY}
      ZEPHYR_BASE_URL: ${ZEPHYR_BASE_URL}
      ZEPHYR_LICENSE_KEY: ${ZEPHYR_LICENSE_KEY}
      TRON_API_KEY: ${TRON_API_KEY}
      TRON_WALLET_ADDRESS: ${TRON_WALLET_ADDRESS}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - tma-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  redis_data:
    driver: local

networks:
  tma-network:
    driver: bridge
